#!/bin/sh

wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.68.tar.bz2
wget http://ftp.gnu.org/gnu/automake/automake-1.11.3.tar.xz
wget http://ftp.gnu.org/gnu/bash/bash-4.2.tar.gz
wget http://ftp.gnu.org/gnu/binutils/binutils-2.22.tar.bz2
wget http://ftp.gnu.org/gnu/bison/bison-2.5.tar.bz2
wget http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
wget http://sourceforge.net/projects/check/files/check/0.9.8/check-0.9.8.tar.gz
wget http://ftp.gnu.org/gnu/coreutils/coreutils-8.15.tar.xz
wget http://ftp.gnu.org/gnu/dejagnu/dejagnu-1.5.tar.gz
wget http://ftp.gnu.org/gnu/diffutils/diffutils-3.2.tar.gz
wget http://prdownloads.sourceforge.net/e2fsprogs/e2fsprogs-1.42.tar.gz
wget http://prdownloads.sourceforge.net/expect/expect5.45.tar.gz
wget ftp://ftp.astron.com/pub/file/file-5.10.tar.gz
wget http://ftp.gnu.org/gnu/findutils/findutils-4.4.2.tar.gz
wget http://prdownloads.sourceforge.net/flex/flex-2.5.35.tar.bz2
wget http://ftp.gnu.org/gnu/gawk/gawk-4.0.0.tar.bz2
wget http://ftp.gnu.org/gnu/gcc/gcc-4.6.2/gcc-4.6.2.tar.bz2
wget http://ftp.gnu.org/gnu/gdbm/gdbm-1.10.tar.gz
wget http://ftp.gnu.org/gnu/gettext/gettext-0.18.1.1.tar.gz
wget http://ftp.gnu.org/gnu/glibc/glibc-2.14.1.tar.bz2
wget http://ftp.gnu.org/gnu/gmp/gmp-5.0.4.tar.xz
wget http://ftp.gnu.org/gnu/grep/grep-2.10.tar.xz
wget http://ftp.gnu.org/gnu/groff/groff-1.21.tar.gz
wget http://ftp.gnu.org/gnu/grub/grub-1.99.tar.gz
wget http://ftp.gnu.org/gnu/gzip/gzip-1.4.tar.gz
wget http://anduin.linuxfromscratch.org/sources/LFS/lfs-packages/conglomeration//iana-etc/iana-etc-2.30.tar.bz2
wget http://ftp.gnu.org/gnu/inetutils/inetutils-1.9.1.tar.gz
wget http://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-3.2.0.tar.xz
wget http://anduin.linuxfromscratch.org/sources/LFS/lfs-packages/conglomeration/kbd/kbd-1.15.2.tar.gz
wget http://packages.profusion.mobi/kmod/kmod-5.tar.xz
wget http://www.greenwoodsoftware.com/less/less-444.tar.gz
wget http://www.linuxfromscratch.org/lfs/downloads/7.1/lfs-bootscripts-20120229.tar.bz2
wget http://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.2.0.tar.gz
wget http://ftp.gnu.org/gnu/libtool/libtool-2.4.2.tar.gz
wget http://www.kernel.org/pub/linux/kernel/v3.x/linux-3.2.6.tar.xz
wget http://ftp.gnu.org/gnu/m4/m4-1.4.16.tar.bz2
wget http://ftp.gnu.org/gnu/make/make-3.82.tar.bz2
wget http://download.savannah.gnu.org/releases/man-db/man-db-2.6.1.tar.gz
wget http://man7.org/linux/download/man-pages/man-pages-3.35.tar.gz
wget http://www.multiprecision.org/mpc/download/mpc-0.9.tar.gz
wget http://www.mpfr.org/mpfr-3.1.0/mpfr-3.1.0.tar.bz2
wget ftp://ftp.gnu.org/gnu/ncurses/ncurses-5.9.tar.gz
wget http://ftp.gnu.org/gnu/patch/patch-2.6.1.tar.bz2
wget http://www.cpan.org/src/5.0/perl-5.14.2.tar.bz2
wget http://procps.sourceforge.net/procps-3.2.8.tar.gz
wget http://prdownloads.sourceforge.net/psmisc/psmisc-22.15.tar.gz
wget http://ftp.gnu.org/gnu/readline/readline-6.2.tar.gz
wget http://ftp.gnu.org/gnu/sed/sed-4.2.1.tar.bz2
wget http://pkg-shadow.alioth.debian.org/releases/shadow-4.1.5.tar.bz2
wget http://www.infodrom.org/projects/sysklogd/download/sysklogd-1.5.tar.gz
wget http://download.savannah.gnu.org/releases/sysvinit/sysvinit-2.88dsf.tar.bz2
wget http://ftp.gnu.org/gnu/tar/tar-1.26.tar.bz2
wget http://prdownloads.sourceforge.net/tcl/tcl8.5.11-src.tar.gz
wget http://ftp.gnu.org/gnu/texinfo/texinfo-4.13a.tar.gz
wget http://www.kernel.org/pub/linux/utils/kernel/hotplug/udev-181.tar.xz
wget http://www.linuxfromscratch.org/lfs/downloads/7.1/udev-config-20100128.tar.bz2
wget http://www.kernel.org/pub/linux/utils/util-linux/v2.20/util-linux-2.20.1.tar.bz2
wget ftp://ftp.vim.org/pub/vim/unix/vim-7.3.tar.bz2
wget http://tukaani.org/xz/xz-5.0.3.tar.bz2
wget http://www.zlib.net/zlib-1.2.6.tar.bz2
wget http://www.linuxfromscratch.org/patches/lfs/7.1/bash-4.2-fixes-4.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/bzip2-1.0.6-install_docs-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/coreutils-8.15-i18n-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/coreutils-8.15-uname-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/flex-2.5.35-gcc44-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/gcc-4.6.2-cross_compile-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/gcc-4.6.2-startfiles_fix-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/glibc-2.14.1-fixes-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/glibc-2.14.1-sort-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/glibc-2.14.1-gcc_fix-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/glibc-2.14.1-cpuid-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/kbd-1.15.2-backspace-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/mpfr-3.1.0-fixes-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/patch-2.6.1-test_fix-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/perl-5.14.2-libc-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/perl-5.14.2-security_fix-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/procps-3.2.8-fix_HZ_errors-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/procps-3.2.8-watch_unicode-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/readline-6.2-fixes-1.patch
wget http://www.linuxfromscratch.org/patches/lfs/7.1/shadow-4.1.5-nscd-1.patch


